version: "3.9"

services:
  user-service:
    build:
      context: ./services/user-service
    container_name: user-service
    environment:
      USER_DB_PATH: /home/appuser/app/data/user_service.db
    ports:
      - "8000:8000"
    volumes:
      - user_data:/home/appuser/app/data

  order-service:
    build:
      context: ./services/order-service
    container_name: order-service
    environment:
      USER_SERVICE_URL: http://user-service:8000
      ORDER_DB_PATH: /home/appuser/app/data/order_service.db
    depends_on:
      - user-service
    ports:
      - "8001:8000"
    volumes:
      - order_data:/home/appuser/app/data

volumes:
  user_data:
  order_data:

