apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - user-service/configmap.yaml
  - user-service/deployment.yaml
  - user-service/service.yaml
  - user-service/pvc.yaml
  - user-service/hpa.yaml
  - order-service/configmap.yaml
  - order-service/deployment.yaml
  - order-service/service.yaml
  - order-service/pvc.yaml
  - order-service/hpa.yaml
  - ingress.yaml
  # Monitoring stack
  - monitoring/prometheus-config.yaml
  - monitoring/prometheus-deployment.yaml
  - monitoring/grafana-deployment.yaml
  - monitoring/grafana-dashboards.yaml
  - monitoring/grafana-dashboard-provisioning.yaml
  - monitoring/loki-config.yaml
  - monitoring/loki-deployment.yaml
  - monitoring/promtail-config.yaml
  - monitoring/promtail-deployment.yaml

